### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by luizcarraro** [marucjmar/emberjs-atom#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 16.04.4
**Thrown From**: [emberjs-atom](https://github.com/marucjmar/emberjs-atom) package 0.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /home/luiz.carraro/.atom/packages/emberjs-atom/lib/provider.coffee:12

TypeError: Cannot read property 'match' of undefined
    at Object.getSuggestions (/packages/emberjs-atom/lib/provider.coffee:12:5)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1792:32)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:996:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:3416:53)
    at TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1381:31)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1661:30)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.2 
atom-handlebars 1.3.0 
atom-monokai 0.10.9 
atom-sublime-monokai-syntax 0.4.4 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.5.6 
autoclose-html 0.23.0 
blame 1.0.1 
browse 1.10.6 
busy 0.7.0 
dark-flat-ui 1.2.4 
emberjs-atom 0.10.0 
file-icons 2.1.19 
fold-functions 0.5.0 
gist 1.1.0 
git-control 0.9.0 
git-plus 7.10.2 
javascript-snippets 1.2.1 
language-liquid 0.6.0 
minimap 4.29.8 
monokai 0.24.0 
monokai-seti 0.9.0 
multi-cursor 2.1.5 
one-dark-shade-ui 0.1.0 
pigments 0.40.2 
Quick-JavaScript 2.2.0 
quick-query 0.12.4 
satisfy-dependencies 0.4.2 
serverless-dashboard 0.2.3 
set-syntax 0.4.0 
seti-ui 1.10.0 
sublime-block-comment 0.5.1 
sublimify 0.10.0 
tag 0.5.0 
text-manipulation 0.6.0 
trailing-spaces 0.4.0 
```

**Comment by marucjmar** [comment]
This plugin is no longer supported, I'm sorry
